services:
  - type: web
    name: petbotphp
    runtime: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /
